In [11]:
import scipy.sparse
import numpy as np
import torch

In [24]:
mat = scipy.sparse.coo_matrix([[0,1,0,2],[1,2,0,0],[0,0,1,1]])

In [13]:
mat.nonzero()

(array([0, 0, 1, 1, 2, 2], dtype=int32),
 array([1, 3, 0, 1, 2, 3], dtype=int32))

In [25]:
mat.row

array([0, 0, 1, 1, 2, 2], dtype=int32)

In [26]:
mat.col

array([1, 3, 0, 1, 2, 3], dtype=int32)

In [16]:
[[i,j] for i,j in zip(mat.row, mat.data)]

[[0, 1], [0, 2], [1, 1], [1, 2], [2, 1], [2, 1]]

In [27]:
mat.data

array([1, 2, 1, 2, 1, 1])

In [17]:
x_tensor = torch.sparse_coo_tensor(indices = np.array([mat.row,mat.col]), values = mat.data, size = mat.shape)


In [18]:
mat.shape

(3, 4)

In [19]:
x_tensor

tensor(indices=tensor([[0, 0, 1, 1, 2, 2],
                       [1, 3, 0, 1, 2, 3]]),
       values=tensor([1, 2, 1, 2, 1, 1]),
       size=(3, 4), nnz=6, layout=torch.sparse_coo)

In [22]:
x_tensor.size(0)

3

In [23]:
type(x_tensor)

torch.Tensor

In [9]:
import numpy as np

array([[0, 0, 1, 1, 2, 2],
       [1, 3, 0, 1, 2, 3]], dtype=int32)

In [14]:
indices = np.array([mat.row,mat.col])

In [15]:
type(indices)

numpy.ndarray

In [19]:
def csr_to_torch_coo(csr_mat):
    coo_mat = csr_mat.tocoo()
    return torch.sparse_coo_tensor(indices = np.array([coo_mat.row,coo_mat.col]), values = coo_mat.data, size = coo_mat.shape)

In [20]:
cmat = scipy.sparse.csr_matrix([[0,1,0,2],[1,2,0,0],[0,0,1,1]])

In [21]:
coo_tensor = csr_to_torch_coo(cmat)

In [22]:
coo_tensor

tensor(indices=tensor([[0, 0, 1, 1, 2, 2],
                       [1, 3, 0, 1, 2, 3]]),
       values=tensor([1, 2, 1, 2, 1, 1]),
       size=(3, 4), nnz=6, layout=torch.sparse_coo)

In [3]:
ser = pd.Series([1,2,3])
type(ser)

pandas.core.series.Series

In [2]:
import pandas as pd

In [6]:
type(ser) == pd.Series

True

In [7]:
ser.dtype

dtype('int64')

In [8]:
ser.dtype == int

True

In [11]:
ser.is_unique

True

In [13]:
import numpy as np

In [14]:
a = np.array([[0,1,0,2],[1,2,0,0],[0,0,1,1]])

In [16]:
a[0,[1,2]]

array([[1, 0],
       [2, 0],
       [0, 1]])

In [22]:
test_ser = pd.Series({'A':1,'B':2})
test_ser2 = pd.Series({'A':1,'C':3})
test_ser3 = pd.Series({'D':1,'C':3})

In [23]:
test_ser

A    1
B    2
dtype: int64

In [24]:
pd.Series(a[0,test_ser.values],index=test_ser.index)

A    1
B    0
dtype: int64

In [29]:
test_ser2.index.intersection(test_ser.index).size

1

In [ ]:
test